site_name: AIOps with IBM Z and LinuxONE
repo_url: https://github.com/mmondics/aiops-z/
site_url: https://mmondics.github.io/aiops-z/
edit_uri: edit/main/docs

nav:
    - Home: 'index.md'
    - Environment Access: 'access.md'
    - Lab Architecture: 'workshop-architecture.md'
    - Presentation: aiops-z_11-21-24.pdf
    - Labs: 
      - Instana: 'labs/instana-lab.md'
      - Turbonomic: 'labs/turbonomic-lab.md'
      - IBM Cloud Pak for AIOps: 'labs/cp4aiops-lab.md'

theme: 
  name: material
  palette:
    scheme: default
    # primary: blue
    font:
      text: IBM Plex Sans
      code: IBM Plex Mono
  features: 
    - search.suggest # adds text completion to search bar
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
  favicon: images/CP4AIOps-logo.svg
  logo: images/CP4AIOps-logo.svg

extra_css:
  - stylesheets/extra.css

copyright: Copyright © 2024 IBM Z Washington Systems Center

plugins:
#  - enumerate-headings:
#      toc_depth: 6
#      strict: true
  - search
  # - htmlproofer:
  #     ignore_urls:
  #       - mailto:*
  #       - https://unit0-wsc.lcsins01.dmz
  - autolinks
  - print-site:
      add_to_navigation: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
